[ITSASU-1307] Standardise agent reference number extraction with tests.

diff --git a/scripts/start b/scripts/start
--- a/scripts/start
+++ b/scripts/start
@@ -7,24 +7,19 @@ function die() {
   exit 1
 }
 
-#MONGO_PORT=27017
-#which nc &>/dev/null && nc -vz localhost $MONGO_PORT 2>/dev/null || die "Can't find MongoDB on port $MONGO_PORT (using: nc -vz localhost $MONGO_PORT)"
+MONGO_PORT=27017
+which nc &>/dev/null && nc -vz localhost $MONGO_PORT 2>/dev/null || die "Can't find MongoDB on port $MONGO_PORT (using: nc -vz localhost $MONGO_PORT)"
+
+SERVICE_PORT=9588
 
 which sm &>/dev/null || die "Can't find Service Manager"
 
-if [[ -z $1 && "$1" == "--minimal" ]]; then
-   sm --start ITSA_SUBSC_DEP
-   sm --start AGENTS_TAX_ENROLMENTS
-   sm --start INCOME_TAX_SUBSCRIPTION
-   sm --start INCOME_TAX_SUBSCRIPTION_SELF_EMPLOYED_FRONTEND
-   sm --start INCOME_TAX_SUBSCRIPTION_STUBS
-   sm --start INCOME_TAX_SUBSCRIPTION_FRONTEND
-   sm --start INCOME_TAX_SUBSCRIPTION_ELIGIBILITY_FRONTEND
-   sm --start TAX_ENROLMENTS
-else
-   sm --start ITSA_SUBSC_ALL
-fi
+which nc &>/dev/null && nc -vz localhost $SERVICE_PORT 2>/dev/null && die "It appears the service is already running?"
+
+sm --start ITSA_SUBSC_MIN "$@"
+sleep 5
 
 sm --stop INCOME_TAX_SUBSCRIPTION_ELIGIBILITY
+sleept 5
 
-sbt "run 9588 -Dapplication.router=testOnlyDoNotUseInAppConf.Routes"
+sbt "run $SERVICE_PORT -Dapplication.router=testOnlyDoNotUseInAppConf.Routes"
